### ISSUE TITLE
Getting http-429 - Too many requests

### ISSUE THREAD

**Issue by masteryodha** [sinopetechnologies/smartThings#12]
To make it short, I have a few sinope thermostat at home and I connected them to the smartthings platform with this github.

But it seems the temperature is not refreshing most of the time.  I have to refresh it manually.

To bypass and test that,  I tried creating a Java springboot app to connect to your API and get the temperature of each of my thermostat.

But in my tests, I seem to be getting a lot of http-429 -- Too many requests. 
I'm in testing phase, but I was wandering what are the rules for this response :  too many requests.

Is it the number of requests that is made or the time between the requests ?

I will modify my code afterward.  My initial goal was to get the temperature of my 8 thermostats every 5 minutes or so.
And even integrate this to Home Assistant.

Thank you

**Comment by SinopeTechSupport** [comment]
Hello,
Communication between Smartthings and our GT125 server can take longer than 5min to be able to get every data from each thermostat. 
And it will be done thermostat per thermostat, so maybe this "too many request" occur because the first thermostat do not have the chance to send all data requested before smartthings begining its second thermostat data request.
You will need to allow delay between each thermostat request to make sure it had time to send all request information. 

Hope this help, let me know if you need more info.

Tommy Ménard Lauzé
Conseiller Support Technique / Technical Support Representative
support@sinopetech.com

**Comment by masteryodha** [comment]
Thanks.

I just pu a sleep of a few secondes between each call and everything seems to work perfectly now.
When I finished testing, I'll put a few minutes between the call so the problem will never occur again.

Thank you for your quick answer.
