### ISSUE TITLE
Can not set thermostat setpoint using Smartthings automation/routines

### ISSUE THREAD

**Issue by jmenzer73** [sinopetechnologies/smartThings#5]
When using a routine in smartthings to set the setpoint of a sinope TH1120RF-3000 thermostat I get the following error:

_9:54:37 PM: error groovy.lang.MissingMethodException: No signature of method: script147658252425833222051.setHeatingSetpoint() is applicable for argument types: (java.math.BigDecimal) values: [55]_

I am able to see thermostat in smartthings and if I change the temperature on Neviweb then it is updated immediately updated on smartthings. 

please a little help with the error from the code.

**Comment by vpepin** [comment]
Hi @jmenzer73,

First, I want to apologize for the delay of answer.

Since your message, the driver has been updated to make it compatible with the automations. If it hasn't already been done, you can simply change the code in your device handler for the new one available and it will be working accordingly.

Thank you and have a good day,

Vanessa Pepin
Technical support agent
Sinopé Technologies
